// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5iSf9CW5P0BeMqEoRgTRAfnT9sGiscc',
    appId: '1:283777561320:web:5b8792eaebbb6fcfe94f5d',
    messagingSenderId: '283777561320',
    projectId: 'grocerystore-536a1',
    authDomain: 'grocerystore-536a1.firebaseapp.com',
    storageBucket: 'grocerystore-536a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAugin5zgEzyV2GN2dKrLz20jiJqfvsJo0',
    appId: '1:283777561320:android:3bc72d610f0add09e94f5d',
    messagingSenderId: '283777561320',
    projectId: 'grocerystore-536a1',
    storageBucket: 'grocerystore-536a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhj62hFNdApWZ8Zgto2zHgIImyOsBa0ho',
    appId: '1:283777561320:ios:9edd1585a6d9c614e94f5d',
    messagingSenderId: '283777561320',
    projectId: 'grocerystore-536a1',
    storageBucket: 'grocerystore-536a1.appspot.com',
    iosBundleId: 'com.example.baqala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhj62hFNdApWZ8Zgto2zHgIImyOsBa0ho',
    appId: '1:283777561320:ios:9edd1585a6d9c614e94f5d',
    messagingSenderId: '283777561320',
    projectId: 'grocerystore-536a1',
    storageBucket: 'grocerystore-536a1.appspot.com',
    iosBundleId: 'com.example.baqala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5iSf9CW5P0BeMqEoRgTRAfnT9sGiscc',
    appId: '1:283777561320:web:ba3a098b8fbb4022e94f5d',
    messagingSenderId: '283777561320',
    projectId: 'grocerystore-536a1',
    authDomain: 'grocerystore-536a1.firebaseapp.com',
    storageBucket: 'grocerystore-536a1.appspot.com',
  );
}
